---
title: "Jenny Wang"
---
## About Me

Hi, my name is Jenny Wang. I am a graduate student at Baruch College pursuing a master's degree in accounting. My career goal is to become a Certified Public Accountant (CPA) and pursue a career in public accounting, with a particular interest in auditing.

[View My Resume](https://docs.google.com/document/d/17AjvxmYnHz1pqt0c5sR_mrytxK9kTpxsOScxq14Z738/edit?usp=sharing)

```{r}
#| echo: false
#| message: false
#| warning: false

if(!require("leaflet")){
    options(repos=c(CRAN="https://cloud.r-project.org"))
    install.packages("leaflet")
    stopifnot(require("leaflet"))
}

baruch_longitude <- -73.98333
baruch_latitude  <- +40.74028

leaflet() |>
  addTiles() |>
  setView(baruch_longitude, baruch_latitude, zoom=17) |>
  addPopups(baruch_longitude, baruch_latitude, 
            "I am a Master's student at <b>Baruch College</b>!")
```
```{r}
#| include: false
1+1
```
--------------
Last Updated: `r format(Sys.time(), "%A %m %d, %Y at %H:%M%p")`